import os
import time
os.system("cls")
print("***********************")
print("***********************")
print("******  HOLA  *********")
print("***********************")
print("***********************")
time.sleep(1)
os.system("cls")
print("***********************")
print("***********************")
print("***   COMO ESTAS   ****")
print("***********************")
print("***********************")
time.sleep(1)
os.system("cls")
print("***********************")
print("***********************")
print("****    ADIOS    ******")
print("***********************")
print("***********************")
time.sleep(1)
os.system("cls")